spring.application.name=trocmarket-backend
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/trocmarket_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.jwt.secret=${JWT_SECRET:trocmarket_secret_key_change_in_production_2024}
app.jwt.expiration=86400000
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# Monetbil — PAS d'espace après les deux-points !
monetbil.service.key=${MONETBIL_SERVICE_KEY:soAR4jzFFniga2dMY00lCooy50WtnQ0G}
monetbil.api.url=https://api.monetbil.com/widget/v2.1
monetbil.notify.url=https://89e0-41-202-219-172.ngrok-free.app